### ISSUE TITLE
best 

### ISSUE THREAD

**Issue by CipherLab600** [wh0Nsq/BypassCredGuard#1]

**Comment by wh0amitz** [comment]
thanks!

**Comment by joshuyaaa** [comment]
可以微信,技术交流一哈

**Comment by wh0amitz** [comment]
ok，this is my wechat：wh0nsq



发自我的iPhone


------------------ Original ------------------
From: joshuyaaa ***@***.***&gt;
Date: Sun,Feb 26,2023 6:03 PM
To: wh0amitz/BypassCredGuard ***@***.***&gt;
Cc: WHOAMI ***@***.***&gt;, State change ***@***.***&gt;
Subject: Re: [wh0amitz/BypassCredGuard] best  (Issue #1)





 
可以微信,技术交流一哈
